Controllers/ConsultasController.cs
using ServicosEPedidos_Mod_17E.Data;
using ServicosEPedidos_Mod_17E.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ServicosEPedidos_Mod_17E.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class ConsultasController : Controller
    {
        private ServicosEPedidos_Mod_17EContext db = new ServicosEPedidos_Mod_17EContext();

        // GET: Consultas
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Index")]
        public ActionResult PesquisaCliente([Bind(Include = "Id,Nome,Email,Morada,Password,Perfil")] Utilizador utilizador)
        {
            string nome = Request.Form["tbNome"];
            var clientes = db.Utilizadors.Where(c => c.Nome.Contains(nome));
            return View("PesquisaCliente", clientes.ToList());
        }










        public ActionResult PesquisaDinamica()
        {
            return View();
        }
        public JsonResult PesquisaNome(string nome)
        {
            var clientes = db.Utilizadors.Where(c => c.Nome.Contains(nome)).ToList();
            var lista = new List<Campos>();
            foreach (var c in clientes)
                lista.Add(new Campos() { nome = c.Nome });
            return Json(lista, JsonRequestBehavior.AllowGet);
        }












        public ActionResult MelhorCliente()
        {
            string sql = @"SELECT Nome, sum(Valor) as valor FROM Pedidoes INNER JOIN utilizadors ON ClienteId=Id GROUP BY ClienteId, nome ORDER BY valor DESC";
            var melhor = db.Database.SqlQuery<Campos>(sql);
            if (melhor != null && melhor.ToList().Count > 0)
                ViewBag.melhor = melhor.ToList()[0];
            else
            {
                Campos temp = new Campos();
                temp.nome = "Não foram encontrados registos";
                ViewBag.melhor = temp;
            }
            return View();
        }
        public ActionResult MelhorPrestador()
        {
            string sql = @"SELECT Nome, count(*) as pedidos FROM PedidoAceites INNER JOIN utilizadors ON PrestadorId=Id GROUP BY nome ORDER BY pedidos DESC";
            var melhor = db.Database.SqlQuery<Campos>(sql);
            if (melhor != null && melhor.ToList().Count > 0)
                ViewBag.melhor = melhor.ToList()[0];
            else
            {
                Campos temp = new Campos();
                temp.nome = "Não foram encontrados registos";
                ViewBag.melhor = temp;
            }
            return View();
        }  

        public class Campos
        {
            public string nome { get; set; }
            public int pedidos{ get; set; }
            public decimal valor { get; set; }
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/LoginController.cs
using ServicosEPedidos_Mod_17E.Data;
using ServicosEPedidos_Mod_17E.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ServicosEPedidos_Mod_17E.Controllers
{

    public class LoginController : Controller
    {
        private ServicosEPedidos_Mod_17EContext db = new ServicosEPedidos_Mod_17EContext();

        // GET: Login
        public ActionResult Index()
        {
            if (User.IsInRole("Cliente") || User.IsInRole("Administrador") || User.IsInRole("Prestador"))
            {
                return RedirectToAction("Index", "Home");

            }
            else
            {

                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Utilizador utilizador)
        {
            if (utilizador.Nome != null && utilizador.Password != null)
            {
                // hash password
                HMACSHA512 hMACSHA512 = new HMACSHA512(new byte[] { 76 });
                var password = hMACSHA512.ComputeHash(Encoding.UTF8.GetBytes(utilizador.Password));
                utilizador.Password = Convert.ToBase64String(password);
                foreach (var u in db.Utilizadors.ToList())
                {
                    if (u.Nome.ToLower() == utilizador.Nome.ToLower() && u.Password == utilizador.Password)
                    {
                        // iniciar sessao
                        FormsAuthentication.SetAuthCookie(utilizador.Nome, false);
                        // redirecionar utilizador
                        if (Request.QueryString["ReturnUrl"] == null)
                        {
                            return RedirectToAction("Index", "Home");
                        }
                        else
                        {
                            return Redirect(Request.QueryString["ReturnUrl"].ToString());
                        }
                    }
                }
            }
            ModelState.AddModelError("", "Login falhou. Tente novamente.");
            return View(utilizador);
        }

        public ActionResult logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index", "Home");

        }
    }
}

Controllers/PedidoAceitesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using ServicosEPedidos_Mod_17E.Data;
using ServicosEPedidos_Mod_17E.Models;

namespace ServicosEPedidos_Mod_17E.Controllers
{
    [Authorize]
    public class PedidoAceitesController : Controller
    {
        private ServicosEPedidos_Mod_17EContext db = new ServicosEPedidos_Mod_17EContext();

        // GET: PedidoAceites
        public ActionResult Index(int? id)
        {

            var pedidoes = db.PedidoAceites.Include(c => c.IdPrest);
            if (User.IsInRole("Prestador"))
            {
                pedidoes = db.PedidoAceites.Where(p => p.PrestadorId == id).Include(c => c.IdPrest);
            }

            //if (User.IsInRole("Prestador"))
            //{
            //    pedidoes = db.Pedidoes.Include(c => c.IdClie);
            //}

            if (pedidoes.ToList().Count == 0)
            {
                ViewBag.mensagem = "Não foram feitos pedidos";
                return View(pedidoes.ToList());
            }

            return View(pedidoes.ToList());

            //var pedidoAceites = db.PedidoAceites.Include(p => p.IdPedido).Include(p => p.IdPrest);
            //return View(pedidoes.ToList());
        }

        // GET: PedidoAceites/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PedidoAceite pedidoAceite = db.PedidoAceites.Find(id);
            if (pedidoAceite == null)
            {
                return HttpNotFound();
            }
            return View(pedidoAceite);
        }

        // GET: PedidoAceites/Create
        [Authorize(Roles = "Prestador")]
        public ActionResult Create()
        {
            ViewBag.PedidoId = new SelectList(db.Pedidoes, "IdPed", "IdPed");
            ViewBag.PrestadorId = new SelectList(db.Utilizadors, "Id", "Nome");
            return View();
        }

        // POST: PedidoAceites/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int id, int ped,[Bind(Include = "IdPedAc,PrestadorId,DataPedAc,PedidoId")] PedidoAceite pedidoAceite)
        {
            if (ModelState.IsValid)
            {
                var data = db.Pedidoes.FirstOrDefault(x => x.IdPed == ped);
                if (data != null)
                {
                    data.Estado = true;
                }

                /////////////////////////////////////
                pedidoAceite.PrestadorId = id;
                pedidoAceite.PedidoId = ped;

                db.PedidoAceites.Add(pedidoAceite);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            ViewBag.PedidoId = new SelectList(db.Pedidoes, "IdPed", "IdPed", pedidoAceite.PedidoId);
            ViewBag.PrestadorId = new SelectList(db.Utilizadors, "Id", "Nome", pedidoAceite.PrestadorId);
            return View(pedidoAceite);
        }

        // GET: PedidoAceites/Edit/5
        /*
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PedidoAceite pedidoAceite = db.PedidoAceites.Find(id);
            if (pedidoAceite == null)
            {
                return HttpNotFound();
            }
            ViewBag.PedidoId = new SelectList(db.Pedidoes, "IdPed", "IdPed", pedidoAceite.PedidoId);
            ViewBag.PrestadorId = new SelectList(db.Utilizadors, "Id", "Nome", pedidoAceite.PrestadorId);
            return View(pedidoAceite);
        }

        // POST: PedidoAceites/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPedAc,PrestadorId,DataPedAc,PedidoId")] PedidoAceite pedidoAceite)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pedidoAceite).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PedidoId = new SelectList(db.Pedidoes, "IdPed", "IdPed", pedidoAceite.PedidoId);
            ViewBag.PrestadorId = new SelectList(db.Utilizadors, "Id", "Nome", pedidoAceite.PrestadorId);
            return View(pedidoAceite);
        }

        // GET: PedidoAceites/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PedidoAceite pedidoAceite = db.PedidoAceites.Find(id);
            if (pedidoAceite == null)
            {
                return HttpNotFound();
            }
            return View(pedidoAceite);
        }

        // POST: PedidoAceites/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PedidoAceite pedidoAceite = db.PedidoAceites.Find(id);
            db.PedidoAceites.Remove(pedidoAceite);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        */
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
@using ServicosEPedidos_Mod_17E.Helper;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Serviços e Pedidos", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @if (Request.IsAuthenticated)
                    {
                        if (User.IsInRole("Administrador"))
                        {
                            <li>@Html.ActionLink("Utilizadores", "Index", "Utilizadores")</li>
                            <li>@Html.ActionLink("Pedidos", "Index", "Pedidos")</li>
                            <li>
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Consultas</a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Pesquisa", "Index", "Consultas")</li>
                                    <li>@Html.ActionLink("Pesquisa Dinamica", "PesquisaDinamica", "Consultas")</li>
                                    <li>@Html.ActionLink("Melhor Cliente", "MelhorCliente", "Consultas")</li>
                                    <li>@Html.ActionLink("Melhor Prestador", "MelhorPrestador", "Consultas")</li>
                                </ul>
                            </li>
                        }
                        else if (User.IsInRole("Prestador"))
                        {
                            <li>@Html.ActionLink("Ver Pedidos", "Index/" + @Html.UserId(User), "Pedidos")</li>
                            <li>@Html.ActionLink("Pedidos Aceites", "Index/" + @Html.UserId(User), "PedidoAceites")</li>
                            // Mudar Para o utilizador ver os pedidos que ele pode aceitar
                        }
                        else if (User.IsInRole("Cliente"))
                        {
                            <li>@Html.ActionLink("Meus Pedidos", "Index/" + @Html.UserId(User), "Pedidos")</li>
                            // Mudar Para o utilizador ver os pedidos feitos por ele
                        }
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                @Html.DisplayName("Olá " + User.Identity.Name)
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Editar perfil", "Edit/" + @Html.UserId(User), "Utilizadores")</li>
                                <li>@Html.ActionLink("Terminar sessão", "Logout", "Login")</li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Index", "Login")</li>
                        <li>@Html.ActionLink("Registo", "Index", "Registo")</li>
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Serviços e Pedidos</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>